[package]
name = "nanopool"
version = "0.1.0"
edition = "2021"

[dependencies]
native-tls = "0.2"
postgres-native-tls = "0.5"
tokio = { version = "1", features = [ "rt-multi-thread" ] }
tokio-postgres = "0.7"
